[package]
name = "fs-telemetry-exporter"
version = "0.1.1"
edition = "2024"

[dependencies]
aflag = "0.1.13"
fxhash = "0.2.1"
promwrite = "0.2.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23" }
walkdir = "2.5.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
