[package]
name = "fs-telemetry-exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
aflag = "0.1.13"

async-stream = "0.3.6"
bytesize = "2.4.2"
fxhash = "0.2.1"
promwrite = "0.1.6"


tokio = { version = "1.53.0", features = [
    "rt-multi-thread",
    "time",
    "macros",
    "fs",
    "signal",
] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
walkdir = "2.5.0"
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
